import React from 'react'

function Team() {
    return (
        <div>
            PGO TEAM
            <br />
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero ipsum minima, mollitia dolore quod amet necessitatibus pariatur assumenda! Corrupti reiciendis numquam maiores quam facere id consequatur quidem nesciunt porro? Praesentium commodi aliquid, necessitatibus quibusdam veritatis voluptates architecto, quasi aliquam error iusto voluptate porro voluptas fugiat! Voluptas debitis voluptate praesentium similique qui voluptatibus vitae distinctio blanditiis, iusto nisi consectetur dolor nemo architecto harum, culpa fugiat totam! Voluptatum at iusto dolorum id accusantium animi voluptate ea doloremque dignissimos vero explicabo magni sequi, unde quis quos eveniet recusandae et possimus perferendis voluptates quam rerum exercitationem. Laborum non dignissimos amet perferendis ut, odit tempora maxime beatae animi voluptatibus dolor cupiditate cumque, quia ullam in aut nihil. Voluptate non dignissimos minus officia quidem harum laboriosam.</p>
            <br />
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae aspernatur in cumque ratione ipsa dolorum, maxime repellat numquam. Dolorum laboriosam tenetur odit similique alias necessitatibus, vel dolores doloremque placeat temporibus deserunt neque, vero sint quidem deleniti magni eveniet minus cupiditate quas quos iste ab earum inventore. Voluptate explicabo corporis eius atque repellat harum dignissimos numquam soluta illum quasi laudantium quibusdam quod, veniam facilis laborum et porro aperiam nobis tempora sequi quaerat consequatur suscipit? Incidunt tempora repudiandae atque, illo quas, cum quos omnis pariatur suscipit nam eligendi, ea perspiciatis exercitationem. Officia maxime tempora, iusto alias perferendis asperiores fugit ex autem? Quae veniam quos alias tempora neque amet expedita minima, est repudiandae facere. In atque mollitia tempora labore sit aspernatur ipsa incidunt eligendi possimus, voluptatibus corporis, obcaecati voluptas culpa, quas error eveniet porro distinctio cupiditate magni sunt. Inventore, expedita doloremque eos qui ipsa iste praesentium quisquam sapiente ullam dolorem consectetur aliquam! Cupiditate nihil sunt provident quae voluptatibus iste quaerat assumenda, exercitationem ratione eum ea aliquam sapiente sint! Temporibus reiciendis sed voluptas molestias fugit animi itaque eaque dicta, soluta sunt laboriosam impedit recusandae, dolorum repudiandae. Vero, placeat ratione. Perspiciatis at officia autem? Odit obcaecati doloribus, aliquid eligendi nisi ad culpa corrupti omnis! Non earum cupiditate eaque eius eveniet facere nobis repudiandae vitae corporis, sunt repellat explicabo quam error debitis ipsam excepturi ab quas recusandae voluptatibus laudantium delectus dicta qui aut. Consequatur omnis magnam incidunt. Ipsa velit cumque modi corrupti inventore quos quas optio, perspiciatis dolor nostrum? Asperiores ab error similique sequi et excepturi repudiandae deleniti nemo atque rem enim, libero unde sunt. Nulla, animi deleniti accusamus amet harum beatae hic magnam incidunt rerum sunt. Iusto hic totam doloremque accusamus eaque culpa minima inventore. Tempore atque ex quia beatae cum culpa. Dolorum temporibus consequatur illum magni voluptates maiores, doloremque eligendi laudantium neque praesentium consectetur!</p>
        </div>
    ) 
}

export default Team
